export const QUERY_KEY = {
  FAQ: {
    LIST: "get-faq-list",
    DETAIL: "get-detail-faq",
    CREATE: "create-faq",
    UPDATE: "update-faq",
    DELETE: "delete-faq",
  },
  BOOKS: {
    LIST: "get-books-list",
    DETAIL: "get-books-detail",
    CREATE: "post-create-book",
    UPDATE: "put-update-book",
    DELETE: "delete-book",
  },
  USERS: {
    LIST: "get-users-list",
    DETAIL: "get-users-detail",
    CREATE: "post-create-user",
    UPDATE: "put-update-user",
    DELETE: "delete-user",
  },
  ROLES: {
    LIST: "get-roles-list",
    DETAIL: "get-roles-detail",
    CREATE: "post-create-role",
    UPDATE: "put-update-role",
    DELETE: "delete-role",
  },
  PERMISSIONS: {
    LIST: "get-permission-list",
    DETAIL: "get-permission-detail",
    CREATE: "post-create-permission",
    UPDATE: "put-update-permission",
    DELETE: "delete-permission",
  },
  USER_MANAGEMENT: {
    LIST: "get-user-management-list",
    DETAIL: "get-user-management-detail",
    CREATE: "post-create-user-management",
    UPDATE: "put-update-user-management",
    DELETE: "delete-user-management",
    APPROVE: "post-approve-user-management",
    REJECT: "post-reject-user-management",
    TOGGLE_STATUS: "post-toggle-user-management-status",
    LOGIN_HISTORY: "get-user-login-history",
    ACTIVATE: "activate-user-management",
    DEACTIVATE: "deactivate-user-management",
  },
  ROLE_MANAGEMENT: {
    LIST: "get-role-management-list",
    DETAIL: "get-role-management-detail",
    CREATE: "post-create-role-management",
    UPDATE: "put-update-role-management",
    DELETE: "delete-role-management",
  },
  COMPANY: {
    LIST: "get-company-list",
    DETAIL: "get-company-detail",
    CREATE: "post-create-company",
    UPDATE: "put-update-company",
    DELETE: "delete-company",
  },
  KURS: {
    LIST: "get-kurs-list",
    DETAIL: "get-kurs-detail",
    CREATE: "post-create-kurs",
    UPDATE: "put-update-kurs",
    DELETE: "delete-kurs",
  },
  RISK: {
    LIST: "get-risk-list",
    DETAIL: "get-risk-detail",
    CREATE: "post-create-risk",
    UPDATE: "put-update-risk",
    DELETE: "delete-risk",
    DELETE_BATCH: "delete-batch-risks",
  },
  ISSUE: {
    LIST: "get-issue-list",
    DETAIL: "get-issue-detail",
    CREATE: "post-create-issue",
    UPDATE: "put-update-issue",
    DELETE: "delete-issue",
    DELETE_BATCH: "delete-batch-issues",
  },
  FEASIBILITY_STUDY: {
    LIST: "get-feasibility-study-list",
    DETAIL: "get-feasibility-study-detail",
    ADD_APPROVER_VIEWER: "post-add-approver-viewer",
    UPDATE_APPROVER_VIEWER: "put-update-approver-viewer",
    DELETE: "delete-feasibility-study",
    SYNC: "post-sync-feasibility-study",
  },
  DROPDOWN: {
    COMPANIES: "get-dropdown-companies",
    TEAM_TYPES: "get-dropdown-team-types",
    USERS: "get-dropdown-users",
    PROJECT_ACTIVITY_TASKS: "get-dropdown-project-activity-tasks",
    PROJECT_STAGES: "get-dropdown-project-stages",
    ACTIVITY_STATUSES: "get-dropdown-activity-statuses",
  },
  PERMIT: {
    LIST: "get-permit-list",
    DETAIL: "get-permit-detail",
    CREATE: "post-create-permit",
    UPDATE: "put-update-permit",
    DELETE: "delete-permit",
  },
  TEMPLATE_MESSAGING: {
    LIST: "get-template-messaging-list",
    DETAIL: "get-template-messaging-detail",
    CREATE: "post-create-template-messaging",
    UPDATE: "put-update-template-messaging",
    DELETE: "delete-template-messaging",
    DELETE_BATCH: "delete-batch-template-messaging",
  },
  MESSAGING: {
    LIST: "get-messaging-list",
    DETAIL: "get-messaging-detail",
    CREATE: "post-create-messaging",
    DELETE: "delete-messaging",
  },
} as const;

type ObjectKey = typeof QUERY_KEY;
type NestedValues<T> = T extends object ? T[keyof T] : never;
export type QueryKey = NestedValues<NestedValues<ObjectKey>>;
